name: new-secrets-read.yaml
run-name: ${{ github.actor }} is reading secrets
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          TEST_ENV_SECRET: ${{ secrets.TEST_ENV_SECRET }}
          TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}
          TEST_REPO_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        run: |
          echo "$TEST_ENV_SECRET $TEST_ENV_VAR $TEST_REPO_SECRET"



